services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab
    restart: always
    ports:
      - '8929:80'    # HTTP
      - '2224:22'    # SSH
    volumes:
      - gitlab-config:/etc/gitlab
      - gitlab-logs:/var/log/gitlab
      - gitlab-data:/var/opt/gitlab
    shm_size: '256m'
    environment:
      - TZ=Pacific/Tahiti      
      - GITLAB_ROOT_PASSWORD=${GITLAB_ROOT_PASSWORD}
    networks:
      - gitlab-network

  gitlab-runner:
    image: gitlab/gitlab-runner:alpine
    container_name: gitlab-runner
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - gitlab-runner-config:/etc/gitlab-runner
    environment:
      - TZ=Europe/Paris
    networks:
      - gitlab-network

volumes:
  gitlab-config:
    external: true
  gitlab-logs:
    external: true
  gitlab-data:
    external: true
  gitlab-runner-config:
    external: true

networks:
  gitlab-network:
    external: true
